using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using AutoAnthonyRelics.Generation;
using BaseLib.Abstracts;
using BaseLib.Extensions;
using BaseLib.Utils;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.Relics;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Enchantments;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.Models.Relics;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.Runs;
using MegaCrit.Sts2.Core.ValueProps;
using Godot;

namespace AutoAnthonyRelics.Models;

/// <summary>
/// A generated relic. Slot-marker subclasses (AnthonyRelic000..) point at
/// their slot; the definition (trigger + independently sampled effects) is a
/// pure function of the run seed, cached in AnthonyRelicRunRegistry.
///
/// TIMING AND OWNERSHIP CONTRACT (each point verified against the engine
/// decompile under sts2-spire1/research/engine-dllsrc or against Qurious's
/// in-game-verified notes on 2026-09-12):
/// - Every hook that fires for ALL listeners must self-gate on owner: the
///   engine broadcasts hooks without an owner filter.
/// - Turn-start ENERGY must be granted from AfterSideTurnStart with
///   TurnNumber &lt;= 1 (vanilla Lantern): BeforeCombatStart grants are
///   overwritten by SetupPlayerTurn's ResetEnergy (Qurious F03).
/// - Turn-1 DRAW changes ride ModifyHandDraw (vanilla BagOfPreparation), not
///   an explicit draw call.
/// - Combat-start BLOCK stays in BeforeCombatStart (vanilla Anchor).
/// - Owner is read only from mutable instances (hooks never fire on canonical
///   instances); IsAllowed / Rarity must not touch Owner.
/// - ModifyHandDraw is a pure query (also called for previews); no side
///   effects there.
/// </summary>
[Pool(typeof(MegaCrit.Sts2.Core.Models.RelicPools.SharedRelicPool))]
public abstract class AnthonyRelicModel : CustomRelicModel
{
    protected abstract int Slot { get; }

    public override bool IsAllowed(IRunState runState)
    {
        // Fragment-pool guard: if startup failed to build the pool, the slots
        // would drop as effect-less placeholders (user report 2026-09-13 class).
        return base.IsAllowed(runState)
            && AutoAnthonyRelicsConfig.Enabled
            && AnthonyRelicRunRegistry.CurrentRunSeed is not null
            && MainFile.FragmentPool.Triggers.Count > 0;
    }

    /// <summary>Never at Neow: the run seed does not exist yet at character select.</summary>
    public override bool IsAllowedAtNeow(Player player)
    {
        return false;
    }

    protected GeneratedRelicDefinition? Definition =>
        AnthonyRelicRunRegistry.DefinitionFor(Slot, MainFile.FragmentPool);

    public override RelicRarity Rarity => Definition?.Rarity ?? RelicRarity.Common;

    // ---------- Description (per-run definition; bilingual by locale) ----------

    public override List<(string, string)>? Localization
    {
        get
        {
            var definition = Definition;
            if (definition is null)
            {
                return new RelicLoc("Generated Relic", "A relic generated by the Anthony algorithm.", RelicText.FlavorEn);
            }
            bool chinese = TranslationServer.GetLocale().StartsWith("zh", StringComparison.OrdinalIgnoreCase);
            string name = chinese ? definition.NameZhs : definition.NameEn;
            string description = chinese ? definition.DescriptionZhs : definition.DescriptionEn;
            string flavor = chinese ? RelicText.FlavorZhs : RelicText.FlavorEn;
            return new RelicLoc(name, description, flavor);
        }
    }

    // ---------- Icons (shared placeholder; per-slot art can be dropped in later) ----------

    public override string PackedIconPath => RelicImagePath($"{Id.Entry.RemovePrefix().ToLowerInvariant()}.png");

    protected override string PackedIconOutlinePath =>
        RelicImagePath($"{Id.Entry.RemovePrefix().ToLowerInvariant()}_outline.png");

    protected override string BigIconPath => BigRelicImagePath($"{Id.Entry.RemovePrefix().ToLowerInvariant()}.png");

    private static string RelicImagePath(string file)
    {
        string path = System.IO.Path.Join(MainFile.ResPath, "images", "relics", file);
        if (ResourceLoader.Exists(path))
        {
            return path;
        }
        return System.IO.Path.Join(MainFile.ResPath, "images", "relics", "relic.png");
    }

    private static string BigRelicImagePath(string file)
    {
        string path = System.IO.Path.Join(MainFile.ResPath, "images", "relics", "big", file);
        if (ResourceLoader.Exists(path))
        {
            return path;
        }
        return System.IO.Path.Join(MainFile.ResPath, "images", "relics", "big", "relic.png");
    }

    /// <summary>
    /// Hover the RELIC -> also show a tooltip for every power it applies
    /// (vanilla Akabeko pattern, user request 2026-09-13).
    /// </summary>
    protected override IEnumerable<IHoverTip> ExtraHoverTips
    {
        get
        {
            var definition = Definition;
            if (definition is null)
            {
                yield break;
            }
            foreach (var effect in definition.Effects)
            {
                if (effect.Opcode != "apply_power")
                {
                    continue;
                }
                Type? powerType = effect.Variant switch
                {
                    "vigor" => typeof(VigorPower),
                    "strength" => typeof(StrengthPower),
                    "thorns" => typeof(ThornsPower),
                    "vulnerable" => typeof(VulnerablePower),
                    _ => null,
                };
                if (powerType is null)
                {
                    continue;
                }
                var tip = s_fromPowerGeneric.Value
                    .MakeGenericMethod(powerType)
                    .Invoke(null, new object?[] { null }) as IHoverTip;
                if (tip is not null)
                {
                    yield return tip;
                }
            }
        }
    }

    /// <summary>Pick the GENERIC FromPower overload explicitly - GetMethod(name)
    /// throws AmbiguousMatchException (two overloads), which aborted the
    /// hover-tip enumeration mid-flight and left the relic detail popup unable
    /// to close.</summary>
    private static readonly Lazy<MethodInfo> s_fromPowerGeneric = new(() =>
        typeof(HoverTipFactory).GetMethods().Single(mi =>
            mi.Name == nameof(HoverTipFactory.FromPower) && mi.IsGenericMethod));

    // ---------- Trigger hooks ----------

    public override async Task BeforeCombatStart()
    {
        // Fuse (L21): this hook is awaited by the engine's turn loop; a throw
        // here marks the combat permanently stuck. Log and degrade instead.
        try
        {
            var (owner, trigger, effects) = Resolve("combat_start");
            if (owner is null || effects is null)
            {
                return;
            }
            if (!MatchesCondition(trigger!.Condition, owner))
            {
                return;
            }
            Flash();
            // handAvailable: false - BeforeCombatStart (:594) precedes StartTurn
            // (:610) and therefore the first draw (:924). Hand effects are applied
            // by the deferred post-draw pass instead.
            await ExecuteEffectsAsync(effects, owner, handAvailable: false);
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] combat-start effect suppressed to keep the combat alive: {e}");
        }
    }

    /// <summary>turn_start_early (vanilla BagOfMarbles: BeforeSideTurnStart).</summary>
    public override async Task BeforeSideTurnStart(PlayerChoiceContext choiceContext, CombatSide side,
        IReadOnlyList<Creature> participants, ICombatState combatState)
    {
        // Fuse (L21): awaited by the engine's turn loop.
        try
        {
            var (owner, trigger, effects) = Resolve("turn_start_early");
            if (owner is null || effects is null)
            {
                return;
            }
            if (!participants.Contains(owner.Creature))
            {
                return;
            }
            if (!MatchesCondition(trigger!.Condition, owner))
            {
                return;
            }
            // Enemy debuffs are ACCUMULATED across all generated relics and applied
            // as ONE merged application at the owner's first turn start (user order
            // 2026-09-13): separate low-count applications each burn one enemy
            // Artifact charge. Only the vulnerable-all fragment is enemy-facing
            // today; the bag is keyed by power type to stay extensible.
            foreach (var effect in effects.Where(e => e.Opcode == "apply_power" && e.Variant == "vulnerable"))
            {
                AccumulateEnemyDebuff<VulnerablePower>(owner, effect.Amount);
            }
            foreach (var effect in effects.Where(e => !(e.Opcode == "apply_power" && e.Variant == "vulnerable")))
            {
                await ExecuteEffectAsync(effect, owner);
            }
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] early turn-start effect suppressed to keep the combat alive: {e}");
        }
    }

    /// <summary>turn_start (vanilla Lantern: energy survives here, not in BeforeCombatStart).</summary>
    public override async Task AfterSideTurnStart(CombatSide side, IReadOnlyList<Creature> participants,
        ICombatState combatState)
    {
        // Fuse (L21): awaited by the engine's turn loop.
        try
        {
            // Extra-turn affix bookkeeping (Pael's Eye AfterSideTurnStart),
            // BEFORE any early return: extra_turn is a passive affix, so a
            // trigger-only path would never reach this and the flag would stay
            // at its initializer forever. Mirrors the engine, which records the
            // flag for the owner's side only and only while unused; a player
            // forced to skip (absent from participants) is recorded as NOT
            // having taken the last player turn, so they cannot claim the extra
            // turn on a turn they never played.
            if (side == Owner.Creature.Side && !_extraTurnUsedThisCombat)
            {
                _wasOwnerPartOfLastPlayerTurn = participants.Contains(Owner.Creature);
            }
            var (owner, trigger, effects) = Resolve("turn_start");
            if (owner is null || effects is null)
            {
                return;
            }
            if (!participants.Contains(owner.Creature))
            {
                return;
            }
            // Flush the merged debuff bag BEFORE this relic's own condition gate:
            // the bag spans all generated relics, so the flush must not depend on
            // any single relic's condition passing.
            if (owner.PlayerCombatState?.TurnNumber <= 1)
            {
                await FlushEnemyDebuffs(owner);
            }
            if (!MatchesCondition(trigger!.Condition, owner))
            {
                return;
            }
            Flash();
            await ExecuteEffectsAsync(effects, owner);
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] turn-start effect suppressed to keep the combat alive: {e}");
        }
    }

    /// <summary>turn_end (vanilla Anchor-family: BeforeSideTurnEnd with participants gate).</summary>
    public override async Task BeforeSideTurnEnd(PlayerChoiceContext choiceContext, CombatSide side,
        IEnumerable<Creature> participants)
    {
        // Fuse (L21): awaited by the engine's turn loop.
        try
        {
            var (owner, trigger, effects) = Resolve("turn_end");
            if (owner is null || effects is null)
            {
                return;
            }
            if (!participants.Contains(owner.Creature))
            {
                return;
            }
            if (!MatchesCondition(trigger!.Condition, owner))
            {
                return;
            }
            Flash();
            await ExecuteEffectsAsync(effects, owner);
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] turn-end effect suppressed to keep the combat alive: {e}");
        }
    }

    public override async Task AfterRoomEntered(AbstractRoom room)
    {
        if (room is not CombatRoom)
        {
            return;
        }
        // Enemy-strength affix, combat-start half. PhilosophersStone applies
        // Strength from BOTH AfterRoomEntered (the combat-start roster) and
        // AfterCreatureAddedToCombat (creatures added mid-combat); the latter's
        // only caller requires an in-progress combat, so on its own it would
        // never fire in a normal fight while the relic text promises it does.
        // Use Owner, not the Resolve result: enemy_strength_gain is passive
        // (no trigger), so Resolve returns null and this call would no-op.
        await ApplyEnemyStrengthAsync(Owner);
        var (owner, trigger, effects) = Resolve("room_entered");
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    // Engine contract (RelicModel.IsTradable): relics with an upon-pickup
    // effect are non-tradable. Our obtain-triggered relics - including the
    // downside-pool curses / max-HP / gold / self-damage pickups - follow the
    // same rule the engine applies to SereTalon / CursedPearl / etc.
    public override bool HasUponPickupEffect => Definition?.Trigger?.Kind == "obtained";

    public override async Task AfterObtained()
    {
        var (owner, trigger, effects) = Resolve("obtained");
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    public override async Task AfterCardPlayed(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        var owner = Owner;
        var definition = Definition;
        if (owner is null || definition?.Trigger is null || definition.Trigger.Kind != "card_played")
        {
            return;
        }
        if (cardPlay.Card.Owner != owner || !CombatManager.Instance.IsInProgress)
        {
            return;
        }
        if (!MatchesCondition(definition.Trigger.Condition, owner, card: cardPlay.Card))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(definition.Effects, owner);
    }

    public override async Task AfterDeath(PlayerChoiceContext choiceContext, Creature target,
        bool wasRemovalPrevented, float deathAnimLength)
    {
        var (owner, trigger, effects) = Resolve("creature_died");
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner, target: target))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    public override async Task AfterGoldGained(Player player)
    {
        var (owner, trigger, effects) = Resolve("gold_gained");
        if (owner is null || player != owner || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    /// <summary>combat_victory (vanilla MeatOnTheBone: AfterCombatVictoryEarly).</summary>
    public override async Task AfterCombatVictoryEarly(CombatRoom room)
    {
        var (owner, trigger, effects) = Resolve("combat_victory");
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    /// <summary>combat_end trigger (ChosenCheese pattern). Also clears the
    /// enemy-debuff merge bag: a combat that ends before the owner's first
    /// turn start never reaches the flush point, and stale amounts must not
    /// leak into the next fight.</summary>
    public override async Task AfterCombatEnd(CombatRoom room)
    {
        var (owner, trigger, effects) = Resolve("combat_end");
        // Per-combat latches reset here (Pael's Eye clears UsedThisCombat in
        // AfterCombatEnd); leaving them set would silently disable the affix
        // for the rest of the run.
        _extraTurnUsedThisCombat = false;
        _wasOwnerPartOfLastPlayerTurn = true;
        // Deferred-hand-effect latch (extra pool): cleared so the next combat's
        // opening hand is enchanted again. The combat state reference alone would
        // usually differ, but clearing explicitly makes the reset independent of
        // whether the engine reuses the state object.
        _deferredHandAppliedState = null;
        _deferredHandAppliedTurn = -1;
        lock (DebuffGate)
        {
            PendingEnemyDebuffs.Clear();
        }
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    public override async Task AfterBlockCleared(Creature creature)
    {
        var (owner, trigger, effects) = Resolve("block_cleared");
        if (owner is null || creature != owner.Creature || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    // ---------- Passive modifiers ----------

    /// <summary>
    /// Passive fragments of THIS relic with the given opcode.
    ///
    /// Every passive override below goes through this, so a passive opcode is
    /// handled uniformly: the generator's PassiveOpcodes set and this file's
    /// overrides are two halves of one contract, and a fragment whose opcode is
    /// in neither simply never reaches a relic.
    /// </summary>
    private IEnumerable<EffectFragment> PassivesWith(string opcode)
    {
        var definition = Definition;
        if (definition is null)
        {
            yield break;
        }
        foreach (EffectFragment effect in definition.Effects)
        {
            if (effect.IsPassive
                && string.Equals(effect.Opcode, opcode, StringComparison.Ordinal)
                && MatchesCondition(effect.Condition, Owner!))
            {
                yield return effect;
            }
        }
    }

    private bool HasPassive(string opcode) => PassivesWith(opcode).Any();

    public override decimal ModifyHandDraw(Player player, decimal count)
    {
        var owner = Owner;
        if (owner is null || player != owner)
        {
            return count;
        }
        foreach (EffectFragment effect in PassivesWith("modify_hand_draw"))
        {
            count += effect.Amount;
        }
        // Floor 1: a 0-card opening hand would brick the run.
        return Math.Max(1m, count);
    }

    /// <summary>Maximum energy (Ancient +1-energy affix family: BlessedAntler,
    /// BloodSoakedRose, Ectoplasm, PhilosophersStone, Sozu, SpikedGauntlets,
    /// VelvetChoker, WhisperingEarring, ...).</summary>
    public override decimal ModifyMaxEnergy(Player player, decimal amount)
    {
        var owner = Owner;
        if (owner is null || player != owner)
        {
            return amount;
        }
        foreach (EffectFragment effect in PassivesWith("modify_max_energy"))
        {
            amount += effect.Amount;
        }
        return amount;
    }

    /// <summary>Restriction: gold gains become 0 (Ectoplasm).</summary>
    public override decimal ModifyGoldGained(Player player, decimal amount)
    {
        var owner = Owner;
        if (owner is null || player != owner || !HasPassive("restrict_gold"))
        {
            return amount;
        }
        return 0m;
    }

    /// <summary>Restriction: the owner cannot obtain potions (Sozu).</summary>
    public override bool ShouldProcurePotion(PotionModel potion, Player player)
    {
        var owner = Owner;
        if (owner is null || player != owner)
        {
            return true;
        }
        return !HasPassive("restrict_potion");
    }

    /// <summary>Restriction: per-turn card-play cap (VelvetChoker). The cap is
    /// the fragment's amount; the engine counts plays itself, so no state is
    /// needed here (the engine's own relic keeps the counter, and our affix is
    /// self-contained because the count is derived from combat history).</summary>
    public override bool ShouldPlay(CardModel card, AutoPlayType autoPlayType)
    {
        var owner = Owner;
        if (owner is null || card.Owner != owner)
        {
            return true;
        }
        int cap = 0;
        foreach (EffectFragment effect in PassivesWith("restrict_card_play"))
        {
            cap = cap == 0 ? effect.Amount : Math.Min(cap, effect.Amount);
        }
        if (cap <= 0)
        {
            return true;
        }
        // Counts EVERY owner card play, auto-play included: VelvetChoker's own
        // AfterCardPlayed increments unconditionally (VelvetChoker.cs:63-71), so
        // filtering auto-plays here would let extra plays past the cap.
        int played = CombatManager.Instance.History.CardPlaysFinished.Count(e =>
            e.Actor == owner.Creature
            && e.HappenedThisTurn(owner.Creature.CombatState));
        return played < cap;
    }

    /// <summary>Restriction: card-effect draws are vetoed (Fiddle). The opening
    /// hand is exempt - CombatManager draws it with fromHandDraw: true
    /// (CombatManager.cs:924), so a relic carrying this affix still draws its
    /// normal hand and the run stays playable. The engine relic also permits
    /// out-of-turn draws (its third guard, side != CurrentSide), which is
    /// mirrored here: Fiddle vetoes only during the owner's own turn.</summary>
    public override bool ShouldDraw(Player player, bool fromHandDraw)
    {
        var owner = Owner;
        if (fromHandDraw || owner is null || player != owner)
        {
            return true;
        }
        if (player.Creature?.CombatState is { } combatState
            && player.Creature.Side != combatState.CurrentSide)
        {
            return true;
        }
        return !HasPassive("restrict_draw");
    }

    /// <summary>Restriction: Power cards cost +1 (SpikedGauntlets).</summary>
    public override bool TryModifyEnergyCostInCombat(CardModel card, decimal originalCost, out decimal modifiedCost)
    {
        modifiedCost = originalCost;
        var owner = Owner;
        if (owner is null || card.Owner?.Creature != owner.Creature || card.Type != CardType.Power)
        {
            return false;
        }
        if (!HasPassive("modify_card_cost"))
        {
            return false;
        }
        modifiedCost = originalCost + 1m;
        return true;
    }

    /// <summary>Benefit: hand is not flushed at end of turn (RunicPyramid).</summary>
    public override bool ShouldFlush(Player player)
    {
        var owner = Owner;
        if (owner is null || player != owner)
        {
            return true;
        }
        return !HasPassive("retain_hand");
    }

    /// <summary>
    /// Benefit: an extra turn when no cards were played (Pael's Eye).
    ///
    /// The once-per-combat latch is REQUIRED, not cosmetic: the engine re-polls
    /// this hook every time the player side ends (CombatManager
    /// SwitchFromPlayerToEnemySide), so without it an empty-handed turn grants
    /// another turn, which draws a fresh hand, which can be played empty again -
    /// an unbounded turn loop. The engine relic bounds it with UsedThisCombat,
    /// set in AfterTakingExtraTurn and cleared in AfterCombatEnd; we mirror both.
    /// </summary>
    public override bool ShouldTakeExtraTurn(Player player)
    {
        var owner = Owner;
        if (owner is null || player != owner || !HasPassive("extra_turn"))
        {
            return false;
        }
        if (_extraTurnUsedThisCombat || !_wasOwnerPartOfLastPlayerTurn)
        {
            return false;
        }
        return !AnyCardsPlayedThisTurn(owner);
    }

    /// <summary>
    /// Benefit: exhausts the hand before granting the extra turn (Pael's Eye).
    ///
    /// Without this the affix is strictly stronger than its text: the engine
    /// relic burns the hand (BeforeSideTurnEndEarly) and only then takes the
    /// extra turn, so "take an extra turn if you play no cards" costs you the
    /// hand you were holding. Granting the turn alone would mean keeping the
    /// hand AND drawing a fresh one - a different, much stronger effect.
    /// Guard set mirrors PaelsEye.cs:110-121 exactly.
    /// </summary>
    public override async Task BeforeSideTurnEndEarly(PlayerChoiceContext choiceContext, CombatSide side,
        IEnumerable<Creature> participants)
    {
        var owner = Owner;
        if (owner is null || !participants.Contains(owner.Creature))
        {
            return;
        }
        if (_extraTurnUsedThisCombat || !HasPassive("extra_turn"))
        {
            return;
        }
        if (AnyCardsPlayedThisTurn(owner))
        {
            return;
        }
        // The engine's fourth guard. Since the BUG 2 fix this flag can genuinely
        // be false (a multiplayer player forced to skip their turn), and without
        // it this hook would burn that player's hand while ShouldTakeExtraTurn
        // correctly refuses the turn - a pure loss, inconsistent with the sibling.
        if (!_wasOwnerPartOfLastPlayerTurn)
        {
            return;
        }
        try
        {
            foreach (CardModel card in PileType.Hand.GetPile(owner).Cards.ToList())
            {
                await CardCmd.Exhaust(choiceContext, card);
            }
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] extra-turn hand exhaust suppressed: {e.Message}");
        }
    }

    /// <summary>
    /// Whether the owner has played a card this turn (Pael's Eye
    /// AnyCardsPlayedThisTurn).
    ///
    /// The history half excludes auto-plays exactly as the engine does. That
    /// exclusion is why the WhisperingEarring clause exists: that relic
    /// auto-plays up to 13 cards on turn 1 (WhisperingEarring.cs
    /// AfterAutoPrePlayPhaseEnteredLate -> CardCmd.AutoPlay), and every one of
    /// them is IsAutoPlay, so the history check cannot see them. Without the
    /// clause an extra_turn relic plus WhisperingEarring would hand out a free
    /// extra turn on turn 1 that the engine relic refuses.
    /// </summary>
    private static bool AnyCardsPlayedThisTurn(Player owner)
    {
        var state = owner.PlayerCombatState;
        if (state is not null && state.TurnNumber == 1
            && owner.Relics.Any(r => r is WhisperingEarring))
        {
            return true;
        }
        return CombatManager.Instance.History.CardPlaysFinished.Any(e =>
            e.Actor == owner.Creature
            && e.HappenedThisTurn(owner.Creature.CombatState)
            && !e.CardPlay.IsAutoPlay);
    }

    /// <summary>Latches the extra turn for this combat (Pael's Eye UsedThisCombat).</summary>
    public override Task AfterTakingExtraTurn(Player player)
    {
        var owner = Owner;
        if (owner is not null && player == owner && HasPassive("extra_turn"))
        {
            _extraTurnUsedThisCombat = true;
        }
        return Task.CompletedTask;
    }

    private bool _extraTurnUsedThisCombat;

    /// <summary>Whether the owner took part in the previous player turn
    /// (Pael's Eye WasOwnerPartOfLastPlayerTurn, initialised true).</summary>
    private bool _wasOwnerPartOfLastPlayerTurn = true;

    /// <summary>Benefit: card rewards draw from every character's pool
    /// (PrismaticGem). Mirrors the engine relic's guard set exactly.</summary>
    public override CardCreationOptions ModifyCardRewardCreationOptions(Player player, CardCreationOptions options)
    {
        var owner = Owner;
        if (owner is null || owner != player)
        {
            return options;
        }
        if (!HasPassive("expand_card_pool"))
        {
            return options;
        }
        if (options.Flags.HasFlag(CardCreationFlags.NoCardPoolModifications)
            || !options.Flags.HasFlag(CardCreationFlags.IsCardReward)
            || options.CardPools.All(p => p.IsColorless))
        {
            return options;
        }
        return options.WithCardPools(player.UnlockState.CharacterCardPools.Union(options.CardPools));
    }

    /// <summary>Benefit: enchant card rewards with Glam (Glitter / SilkenTress).</summary>
    public override bool TryModifyCardRewardOptionsLate(Player player, List<CardCreationResult> cardRewards,
        CardCreationOptions options)
    {
        var owner = Owner;
        if (owner is null || player != owner || !HasPassive("enchant_reward"))
        {
            return false;
        }
        if (!options.Flags.HasFlag(CardCreationFlags.IsCardReward))
        {
            return false;
        }
        Glam glam = ModelDb.Enchantment<Glam>();
        foreach (CardCreationResult reward in cardRewards)
        {
            CardModel card = reward.Card;
            if (!glam.CanEnchant(card))
            {
                continue;
            }
            CardModel clone = owner.RunState.CloneCard(card);
            CardCmd.Enchant<Glam>(clone, 1m);
            reward.ModifyCard(clone, this);
        }
        return true;
    }

    /// <summary>
    /// Restriction: enemies gain Strength (PhilosophersStone).
    ///
    /// Applied from two hooks, mirroring the engine relic: the combat-start
    /// roster (AfterRoomEntered) and creatures added mid-combat
    /// (AfterCreatureAddedToCombat). Applying only from the latter would make
    /// the affix dead in every normal fight - its sole caller requires an
    /// already-in-progress combat.
    /// </summary>
    private async Task ApplyEnemyStrengthAsync(Player? owner)
    {
        if (owner?.Creature?.CombatState is null)
        {
            return;
        }
        int amount = PassivesWith("enemy_strength_gain").Sum(e => e.Amount);
        if (amount <= 0)
        {
            return;
        }
        try
        {
            var enemies = owner.Creature.CombatState.GetOpponentsOf(owner.Creature)
                .Where(c => c.IsAlive);
            await PowerCmd.Apply<StrengthPower>(new ThrowingPlayerChoiceContext(), enemies,
                amount, null, null);
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] enemy strength affix suppressed: {e.Message}");
        }
    }

    public override async Task AfterCreatureAddedToCombat(Creature creature)
    {
        var owner = Owner;
        if (owner is null || creature.Side == owner.Creature.Side)
        {
            return;
        }
        int amount = PassivesWith("enemy_strength_gain").Sum(e => e.Amount);
        if (amount <= 0)
        {
            return;
        }
        try
        {
            await PowerCmd.Apply<StrengthPower>(new ThrowingPlayerChoiceContext(), creature,
                amount, null, null);
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] enemy strength affix suppressed: {e.Message}");
        }
    }

    // ---------- Condition evaluation (stateless by design) ----------

    private bool MatchesCondition(string? condition, Player owner, CardModel? card = null, Creature? target = null)
    {
        switch (condition)
        {
            case null:
            case "":
                return true;
            case "first_turn":
                return owner.PlayerCombatState?.TurnNumber <= 1;
            case "turn_equals_2":
                return owner.PlayerCombatState?.TurnNumber == 2;
            case "turn_equals_3":
                return owner.PlayerCombatState?.TurnNumber == 3;
            case "hp_below_half":
                return owner.Creature.CurrentHp * 2m <= owner.Creature.MaxHp;
            case "hand_empty":
                return PileType.Hand.GetPile(owner).IsEmpty;
            case "no_attack_played_this_turn":
                return !CombatManager.Instance.History.CardPlaysFinished.Any(e =>
                    e.HappenedThisTurn(owner.Creature.CombatState)
                    && e.CardPlay.Card.Type == CardType.Attack
                    && e.CardPlay.Player == owner);
            case "card_type_power":
                return card is not null && card.Type == CardType.Power;
            case "enemy_side":
                return target is not null && owner.Creature is not null && target.Side != owner.Creature.Side;
            default:
                throw new InvalidOperationException($"unknown relic condition '{condition}' (ledger/generator drift)");
        }
    }

    // ---------- Enemy-debuff merge (one Apply per power per combat) ----------

    private static readonly object DebuffGate = new();
    // Keyed by OWNER IDENTITY (second-round review, 2026-09-13): in
    // multiplayer every client hosts relic instances for ALL players, and a
    // process-global bag would merge two players' debuffs into whoever's
    // turn start flushes first. ulong 0 = single-player fallback.
    // Owner-0 reachability (third-round AAR-6): the 0 bucket exists only when
    // NetId is unset, i.e. single-player, where exactly one player exists -
    // two owners can never share the 0 bucket; MP players always carry real
    // NetIds. Bags flush on their owner's turn start and the whole map clears
    // on combat end; StS2 has no overlapping combat states.
    private static readonly Dictionary<ulong, Dictionary<Type, int>> PendingEnemyDebuffs = new();

    private static ulong OwnerKey(Player? owner) => owner?.NetId ?? 0;

    private void AccumulateEnemyDebuff<T>(Player owner, int amount) where T : PowerModel
    {
        if (amount <= 0)
        {
            return;
        }
        lock (DebuffGate)
        {
            var bag = PendingEnemyDebuffs.TryGetValue(OwnerKey(owner), out var existing)
                ? existing
                : (PendingEnemyDebuffs[OwnerKey(owner)] = new Dictionary<Type, int>());
            bag[typeof(T)] = bag.GetValueOrDefault(typeof(T)) + amount;
        }
    }

    private static async Task FlushEnemyDebuffs(Player owner)
    {
        KeyValuePair<Type, int>[] pending;
        lock (DebuffGate)
        {
            if (!PendingEnemyDebuffs.TryGetValue(OwnerKey(owner), out var bag)
                || bag.Count == 0)
            {
                return;
            }
            pending = bag.ToArray();
            PendingEnemyDebuffs.Remove(OwnerKey(owner));
        }
        var context = new ThrowingPlayerChoiceContext();
        var enemies = owner.Creature.CombatState?.HittableEnemies ?? Array.Empty<Creature>();
        if (enemies.Count == 0)
        {
            return;
        }
        foreach (var entry in pending)
        {
            var closed = s_vulnerableApply.MakeGenericMethod(entry.Key);
            // SIX arguments: the optional `bool silent = false` is the 6th
            // parameter, and MethodInfo.Invoke does NOT fill optional-param
            // defaults - the 5-arg call threw TargetParameterCountException
            // inside the engine's turn loop and froze the combat (Act 4
            // report 2026-09-13).
            var task = (Task)closed.Invoke(null,
                new object?[] { context, enemies, (decimal)entry.Value, owner.Creature, null, false })!;
            await task;
        }
    }

    private static readonly MethodInfo s_vulnerableApply =
        typeof(PowerCmd).GetMethods()
            .Single(m => m.Name == nameof(PowerCmd.Apply)
                && m.IsGenericMethod
                && m.GetParameters()[1].ParameterType == typeof(IEnumerable<Creature>));

    // ---------- Effect execution ----------

    private (Player? owner, TriggerFragment? trigger, IReadOnlyList<EffectFragment>? effects) Resolve(string kind)
    {
        var definition = Definition;
        Player? owner = Owner;
        if (definition?.Trigger is null || owner is null || definition.Trigger.Kind != kind)
        {
            return (null, null, null);
        }
        return (owner, definition.Trigger, definition.Effects);
    }

    // Combat-scoped opcodes (matched by opcode alone): their engine commands
    // need a live combat context (energy / enemies / draw pile) and NRE
    // outside combat - an Ancient-event pickup fired gain_energy with no
    // PlayerCombatState, killing the obtain chain and freezing the game's UI
    // in a render loop (real incident 2026-09-14). Run-scoped opcodes (heal,
    // gain_max_hp, gain_gold, gain_max_potion, modify_hand_draw) are safe.
    //
    // The set lives on EffectFragment (single definition shared with the
    // generator, which refuses to pair one of these opcodes with a trigger that
    // has no combat context - RelicGenerator.Excluded rule 4). Two copies would
    // let generation and execution drift apart, which is exactly the defect
    // WS-0916-05 describes.
    private static bool IsCombatScoped(string opcode) =>
        EffectFragment.CombatScopedOpcodes.Contains(opcode);

    // Downside pool (user order 2026-09-15): curse fragments carry the source
    // relic's exact curse card in their Variant. AddCurseToDeck<T> is generic
    // with no non-generic overload, so resolution goes through reflection -
    // the fragment set is closed and probe-verified; a miss is a fuse-caught
    // throw, never a silent no-op.
    private static readonly Dictionary<string, Type> CurseTypes = new(StringComparer.Ordinal)
    {
        ["greed"] = typeof(MegaCrit.Sts2.Core.Models.Cards.Greed),
        ["curse_of_the_bell"] = typeof(MegaCrit.Sts2.Core.Models.Cards.CurseOfTheBell),
        ["enthralled"] = typeof(MegaCrit.Sts2.Core.Models.Cards.Enthralled),
        ["folly"] = typeof(MegaCrit.Sts2.Core.Models.Cards.Folly),
    };

    private static readonly MethodInfo? s_addCurse =
        typeof(CardPileCmd).GetMethod("AddCurseToDeck", new[] { typeof(Player) });

    /// <param name="handAvailable">
    /// False only for the hooks that fire BEFORE the turn's draw, i.e.
    /// BeforeCombatStart (`combat_start`). The hand does not exist there, so a
    /// hand effect run inline would iterate zero cards and silently do nothing;
    /// those are applied by the deferred post-draw pass instead
    /// (AfterPlayerTurnStartLate). Every other hook fires after the draw and
    /// passes the default true - notably `turn_start` (AfterSideTurnStart),
    /// which runs only after :778 has awaited the SetupPlayerTurn task whose
    /// :924 draws.
    /// </param>
    private async Task ExecuteEffectsAsync(IReadOnlyList<EffectFragment> effects, Player owner,
        bool handAvailable = true)
    {
        var context = new ThrowingPlayerChoiceContext();
        foreach (EffectFragment effect in effects)
        {
            if (!handAvailable && effect.IsHandEffect)
            {
                continue;
            }
            try
            {
                await ExecuteEffectAsync(effect, owner, context);
            }
            catch (Exception e)
            {
                // Per-effect fuse: one broken effect must not break the whole
                // obtain chain / trigger pipeline (2026-09-14 freeze incident).
                MainFile.Logger.Error($"[{MainFile.ModId}] effect {effect.Opcode}/{effect.Variant} failed; continuing: {e.Message}");
            }
        }
    }

    private async Task ExecuteEffectAsync(EffectFragment effect, Player owner,
        ThrowingPlayerChoiceContext? context = null)
    {
        context ??= new ThrowingPlayerChoiceContext();
        {
            if (IsCombatScoped(effect.Opcode) && owner.PlayerCombatState is null)
            {
                // Out-of-combat guard: this trigger fired outside any combat
                // (obtain / gold-gained / run-level hooks) - the combat-scoped
                // command would NRE, so degrade to a skipped effect instead.
                // Generation-time eligibility (RelicGenerator.Excluded rule 4)
                // means a generated relic can no longer reach this line; the
                // guard stays as the executor's own backstop for hand-written or
                // save-migrated definitions.
                MainFile.Logger.Info($"[{MainFile.ModId}] effect {effect.Opcode}/{effect.Variant} skipped: no combat context at this trigger");
                return;
            }
            int amount = effect.Amount;
            switch (effect.Opcode, effect.Variant, effect.Target)
            {
                case ("apply_power", "vigor", "self"):
                    await PowerCmd.Apply<VigorPower>(context, owner.Creature, amount, owner.Creature, null);
                    break;
                case ("apply_power", "strength", "self"):
                    await PowerCmd.Apply<StrengthPower>(context, owner.Creature, amount, owner.Creature, null);
                    break;
                case ("apply_power", "thorns", "self"):
                    await PowerCmd.Apply<ThornsPower>(context, owner.Creature, amount, owner.Creature, null);
                    break;
                case ("apply_power", "vulnerable", "all_enemies"):
                    await PowerCmd.Apply<VulnerablePower>(context,
                        owner.Creature.CombatState?.HittableEnemies ?? Array.Empty<Creature>(),
                        amount, owner.Creature, null);
                    break;
                case ("gain_block", _, "self"):
                    await CreatureCmd.GainBlock(owner.Creature, amount, ValueProp.Unpowered, null);
                    break;
                case ("heal", _, "self"):
                    await CreatureCmd.Heal(owner.Creature, amount);
                    break;
                case ("gain_energy", _, "self"):
                    await PlayerCmd.GainEnergy(amount, owner);
                    break;
                case ("draw_cards", _, "self"):
                    await CardPileCmd.Draw(context, amount, owner);
                    break;
                case ("gain_max_hp", _, "self"):
                    await CreatureCmd.GainMaxHp(owner.Creature, amount);
                    break;
                case ("gain_gold", _, "self"):
                    await PlayerCmd.GainGold(amount, owner);
                    break;
                case ("gain_max_potion", _, "self"):
                    await PlayerCmd.GainMaxPotionCount(amount, owner);
                    break;
                case ("deal_damage", _, "all_enemies"):
                    await CreatureCmd.Damage(context,
                        owner.Creature.CombatState?.HittableEnemies ?? Array.Empty<Creature>(),
                        amount, ValueProp.Unpowered, owner.Creature, null, null);
                    break;
                case ("modify_hand_draw", _, "self"):
                    // Handled by the ModifyHandDraw query override; nothing to run.
                    break;
                // Downside pool (user order 2026-09-15): source-exact shapes.
                case ("lose_hp", "unblockable", "self"):
                    // True HP loss, engine ValueProp.Unblockable | Unpowered
                    // (RoyalPoison / FragrantMushroom).
                    await CreatureCmd.Damage(context, owner.Creature, amount,
                        ValueProp.Unblockable | ValueProp.Unpowered, null, null);
                    break;
                case ("lose_hp", _, "self"):
                    // Blockable self-damage (PrecariousShears passes a plain
                    // Unpowered DamageVar).
                    await CreatureCmd.Damage(context, owner.Creature, amount,
                        ValueProp.Unpowered, null, null);
                    break;
                case ("lose_max_hp", _, "self"):
                    await CreatureCmd.LoseMaxHp(context, owner.Creature, amount, isFromCard: false);
                    break;
                case ("lose_gold", "all", "self"):
                    // SilkenTress: the whole purse.
                    await PlayerCmd.LoseGold(owner.Gold, owner);
                    break;
                case ("lose_gold", _, "self"):
                    // SealOfGold guards on gold >= amount before paying; mirror
                    // it so a broke player is not driven negative.
                    if (owner.Gold >= amount)
                    {
                        await PlayerCmd.LoseGold(amount, owner);
                    }
                    break;
                case ("add_curse", _, _):
                    await AddCurseAsync(effect, owner);
                    break;
                // ---- Extra pool (user order 2026-09-18), ported from
                // QuriousCraftingRelics' extra catalog. TIMING is the load-bearing
                // part here, not the commands (verified in CombatManager):
                //
                // * `turn_start` (AfterSideTurnStart, :783) HAS a hand: :778
                //   awaits the SetupPlayerTurn task whose :924 draws, and :783
                //   runs only after that. These run inline.
                // * `combat_start` (BeforeCombatStart, :594) runs before StartTurn
                //   (:610) and therefore before any draw - a hand effect there
                //   would iterate an empty hand, so BeforeCombatStart passes
                //   handAvailable:false and the deferred pass applies them
                //   (RunHandEffects). Qurious hit the same wall
                //   (ChaosRelicModel.cs:519).
                // * `enchant_deck` targets the MASTER DECK, which exists outside
                //   combat, so it runs inline at its `obtained` trigger.
                case ("retain_hand_card", _, "self"):
                case ("sly_hand_card", _, "self"):
                case ("ethereal_hand_card", _, "self"):
                case ("enchant_hand", _, "self"):
                    RunHandEffects(new[] { effect }, owner);
                    break;
                case ("enchant_deck", _, "self"):
                    EnchantDeck(effect, owner);
                    break;
                default:
                    throw new InvalidOperationException(
                        $"unsupported relic effect {effect.Opcode}/{effect.Variant}/{effect.Target} on atom(s) {string.Join(",", effect.SourceAtoms)}");
            }
        }
    }

    /// <summary>
    /// Deferred hand-effect pass (extra pool, user order 2026-09-18) for the
    /// `combat_start` trigger only.
    ///
    /// `combat_start` is BeforeCombatStart (CombatManager:594), which runs before
    /// StartTurn (:610) and therefore before the first draw (:924) - so a hand
    /// effect applied there iterates an EMPTY hand and silently does nothing.
    /// This pass re-applies those effects after the draw. QuriousCraftingRelics
    /// hit the same wall and moved its combat-start enchants here too
    /// (ChaosRelicModel.cs:519 "the hand is empty and every enchant loop
    /// iterated zero cards").
    ///
    /// Why not simply retarget the atom to `turn_start` instead: the trigger
    /// carries the relic's TEXT and its lifetime. `combat_start` reads as a
    /// once-per-combat opening effect, `turn_start` as every turn. Deferring
    /// keeps the source's meaning and is the smaller lie than re-labelling a
    /// once-per-combat affix as a per-turn one.
    ///
    /// Turn gate: `turn &lt;= 1` is what "combat start" means for a hand effect -
    /// one opening-hand enchant, not one per turn - and is exactly Qurious's
    /// gate for the same reason (ChaosRelicModel.cs:522).
    /// </summary>
    public override Task AfterPlayerTurnStartLate(PlayerChoiceContext choiceContext, Player player)
    {
        // Fuse (L21): awaited by the engine's turn loop.
        try
        {
            var (owner, trigger, effects) = Resolve("combat_start");
            if (owner is null || effects is null || owner != player)
            {
                return Task.CompletedTask;
            }
            if (player.PlayerCombatState?.TurnNumber > 1)
            {
                return Task.CompletedTask;
            }
            // Duplicate-invocation guard. The engine broadcasts this hook once
            // per model per turn, but hook-refiring frameworks (RitsuLib is
            // installed alongside this mod) re-invoke it; without the guard the
            // opening hand would be enchanted once per refire. Qurious guards
            // the same hook the same way (ChaosRelicModel.cs:510, keyed on the
            // combat state + turn number). Keyed per relic instance, so it also
            // survives a mid-combat combat-state replacement.
            var combatState = player.PlayerCombatState;
            if (ReferenceEquals(_deferredHandAppliedState, combatState) && _deferredHandAppliedTurn == 1)
            {
                return Task.CompletedTask;
            }
            if (!MatchesCondition(trigger!.Condition, owner))
            {
                return Task.CompletedTask;
            }
            _deferredHandAppliedState = combatState;
            _deferredHandAppliedTurn = 1;
            RunHandEffects(effects, owner);
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] deferred hand effect suppressed to keep the combat alive: {e}");
        }
        return Task.CompletedTask;
    }

    // Deferred-pass bookkeeping (see AfterPlayerTurnStartLate). Reset with the
    // other per-combat flags in AfterCombatEnd, so a new combat applies again.
    private PlayerCombatState? _deferredHandAppliedState;
    private int _deferredHandAppliedTurn = -1;

    /// <summary>
    /// Apply this relic's hand-targeted effects (extra pool). One shared
    /// selection helper serves all four opcodes rather than four near-identical
    /// loops: the difference between them is only what is done to the chosen
    /// cards.
    ///
    /// Selection is RANDOM over the eligible hand, not player-chosen: AAR has no
    /// interactive selection path (the executor runs under
    /// ThrowingPlayerChoiceContext, which throws on any player choice), unlike
    /// Qurious which has a full CardSelectCmd flow. Random-over-eligible is the
    /// honest behaviour for a passive relic affix and matches the mod's
    /// non-interactive trigger model.
    /// </summary>
    private void RunHandEffects(IReadOnlyList<EffectFragment> effects, Player owner)
    {
        foreach (EffectFragment effect in effects.Where(e => e.IsHandEffect))
        {
            int amount = effect.Amount;
            if (amount <= 0)
            {
                continue;
            }
            var hand = PileType.Hand.GetPile(owner).Cards.ToList();
            if (hand.Count == 0)
            {
                continue;
            }
            Flash();
            switch (effect.Opcode)
            {
                case "retain_hand_card":
                    foreach (CardModel card in PickHand(owner, hand, amount, static _ => true))
                    {
                        card.GiveSingleTurnRetain();
                    }
                    break;
                case "sly_hand_card":
                    foreach (CardModel card in PickHand(owner, hand, amount, static _ => true))
                    {
                        card.GiveSingleTurnSly();
                    }
                    break;
                case "ethereal_hand_card":
                    // Exclude already-Ethereal cards: the keyword is permanent on
                    // the instance, so re-adding it burns one of the `amount`
                    // picks for nothing.
                    foreach (CardModel card in PickHand(owner, hand, amount,
                        static c => !c.Keywords.Contains(CardKeyword.Ethereal)))
                    {
                        card.AddKeyword(CardKeyword.Ethereal);
                    }
                    break;
                case "enchant_hand":
                    // Level 1 per chosen card: for `enchant_hand` the amount is
                    // a card COUNT ("enchant up to N cards"), not a level.
                    foreach (CardModel card in PickHand(owner, hand, amount,
                        c => CanEnchant(c, effect.Variant)))
                    {
                        EnchantCard(card, effect.Variant!, 1);
                    }
                    break;
            }
        }
    }

    /// <summary>
    /// Apply a deck-wide enchant at obtain time (extra pool). The master deck
    /// exists outside combat, so unlike the hand effects this runs inline.
    /// Mirrors QuriousCraftingRelics' X_PICKUP_* behaviour: ONE random eligible
    /// deck card.
    ///
    /// RNG channel: <c>UpFront</c> is correct HERE (unlike the hand path, which
    /// uses CombatCardSelection): this fires at `obtained`, outside combat, and
    /// Qurious's equivalent pickup enchant uses the same channel
    /// (ChaosRelicModel.cs:1017).
    ///
    /// The enchant LEVEL is <c>effect.Amount</c>, not 1: the relic text renders
    /// `amount` as the level for this opcode ("enchant a random Attack card in
    /// your deck with {amount} Sharp"), and the ledger's Values are the
    /// documented tuning knob, so hardcoding 1 would silently desync the two the
    /// moment an amount is edited. (The hand path's per-card 1 is correct there,
    /// because for `enchant_hand` the amount is a card COUNT.)
    /// </summary>
    private void EnchantDeck(EffectFragment effect, Player owner)
    {
        if (effect.Variant is null)
        {
            throw new InvalidOperationException(
                $"enchant_deck without a variant on atom(s) {string.Join(",", effect.SourceAtoms)}");
        }
        int level = effect.Amount;
        if (level <= 0)
        {
            return;
        }
        var deck = PileType.Deck.GetPile(owner).Cards;
        if (deck.Count == 0)
        {
            return;
        }
        var eligible = deck.Where(c => CanEnchant(c, effect.Variant)).ToList();
        if (eligible.Count == 0)
        {
            MainFile.Logger.Info($"[{MainFile.ModId}] enchant_deck {effect.Variant}: no eligible deck card");
            return;
        }
        Flash();
        CardModel? card = owner.RunState.Rng.UpFront.NextItem(eligible);
        if (card is not null)
        {
            EnchantCard(card, effect.Variant, level);
        }
    }

    /// <summary>
    /// Choose up to <paramref name="count"/> eligible cards from the hand.
    ///
    /// RNG CHANNEL (corrected 2026-09-19): <c>CombatCardSelection</c>, which
    /// RunRngSet documents as "cards that are randomly chosen during combat by
    /// things like True Grit" and which the engine's own card-picking relics use
    /// (TrueGrit.cs:40, Cinder.cs:35, Thrash.cs:50, MummifiedHand.cs:30,
    /// JeweledMask.cs:32). This first used <c>UpFront</c>, which is the
    /// RUN-GENERATION stream - "which monsters you'll fight / which events /
    /// which relics you'll be offered" (RunRngSet.cs:29-33) - so consuming it at
    /// every turn start shifted all later act, map and relic rolls for the run.
    /// </summary>
    private static List<CardModel> PickHand(Player owner, List<CardModel> hand, int count,
        Func<CardModel, bool> eligible)
    {
        var pool = hand.Where(eligible).ToList();
        var picked = new List<CardModel>(Math.Min(count, pool.Count));
        var rng = owner.RunState.Rng.CombatCardSelection;
        while (picked.Count < count && pool.Count > 0)
        {
            CardModel? card = rng.NextItem(pool);
            if (card is null)
            {
                break;
            }
            pool.Remove(card);
            picked.Add(card);
        }
        return picked;
    }

    /// <summary>
    /// Enchant eligibility. The engine's own CanEnchant is what enforces the
    /// card-type restriction (Sharp = Attack, Nimble = GainsBlock, Imbued =
    /// Skill) and the one-enchantment-slot rule - and it is REQUIRED, because
    /// CardCmd.Enchant THROWS InvalidOperationException on an ineligible card
    /// (CardCmd.cs:537) rather than returning null.
    ///
    /// DIFFERENCE FROM QURIOUS (2026-09-19): Qurious's
    /// <c>CanTakeEnchant</c> deliberately bypasses the engine's non-stackable
    /// rejection so a same-type re-enchant can LEVEL UP an existing
    /// enchantment, paired with its own <c>EnchantWithStacking</c>. This mod
    /// does NOT: vanilla's last branch rejects any card that already carries an
    /// enchantment (Sharp/Nimble/Imbued all leave IsStackable false,
    /// EnchantmentModel.cs:173), so an already-enchanted card is skipped and a
    /// level can never be raised by a second affix. That is a deliberate
    /// behaviour choice for this mod (each generated relic enchants untouched
    /// cards), not parity with Qurious.
    /// </summary>
    private static bool CanEnchant(CardModel card, string? variant) => variant switch
    {
        "sharp" => ModelDb.Enchantment<Sharp>().CanEnchant(card),
        "nimble" => ModelDb.Enchantment<Nimble>().CanEnchant(card),
        "imbued" => ModelDb.Enchantment<Imbued>().CanEnchant(card),
        _ => false,
    };

    /// <summary>
    /// Enchant a card with <paramref name="level"/> levels. The variant is DATA,
    /// so the generic <c>CardCmd.Enchant&lt;T&gt;</c> cannot be called directly;
    /// the closed three-case switch is the honest form of that dispatch. It
    /// resolves the same public overload the generic form does (CardCmd.cs:520
    /// delegates to :534) and, like it, takes a MUTABLE copy - passing the
    /// canonical instance would fail the command's own AssertMutable.
    /// An unknown variant throws into the effect fuse, never a silent no-op.
    /// </summary>
    private static void EnchantCard(CardModel card, string variant, int level)
    {
        switch (variant)
        {
            case "sharp":
                CardCmd.Enchant<Sharp>(card, level);
                break;
            case "nimble":
                CardCmd.Enchant<Nimble>(card, level);
                break;
            case "imbued":
                CardCmd.Enchant<Imbued>(card, level);
                break;
            default:
                throw new InvalidOperationException($"unsupported enchantment variant {variant}");
        }
    }


    private async Task AddCurseAsync(EffectFragment effect, Player owner)
    {
        if (s_addCurse is null || !CurseTypes.TryGetValue(effect.Variant ?? "", out Type? curseType))
        {
            throw new InvalidOperationException(
                $"unsupported curse variant {effect.Variant} on atom(s) {string.Join(",", effect.SourceAtoms)}");
        }
        var task = (Task)s_addCurse.MakeGenericMethod(curseType).Invoke(null, new object?[] { owner })!;
        await task;
    }
}
