using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using AutoAnthonyRelics.Generation;
using BaseLib.Abstracts;
using BaseLib.Extensions;
using BaseLib.Utils;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.Relics;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.Runs;
using MegaCrit.Sts2.Core.ValueProps;
using Godot;

namespace AutoAnthonyRelics.Models;

/// <summary>
/// A generated relic. Slot-marker subclasses (AnthonyRelic000..) point at
/// their slot; the definition (trigger + independently sampled effects) is a
/// pure function of the run seed, cached in AnthonyRelicRunRegistry.
///
/// TIMING AND OWNERSHIP CONTRACT (each point verified against the engine
/// decompile under sts2-spire1/research/engine-dllsrc or against Qurious's
/// in-game-verified notes on 2026-09-12):
/// - Every hook that fires for ALL listeners must self-gate on owner: the
///   engine broadcasts hooks without an owner filter.
/// - Turn-start ENERGY must be granted from AfterSideTurnStart with
///   TurnNumber &lt;= 1 (vanilla Lantern): BeforeCombatStart grants are
///   overwritten by SetupPlayerTurn's ResetEnergy (Qurious F03).
/// - Turn-1 DRAW changes ride ModifyHandDraw (vanilla BagOfPreparation), not
///   an explicit draw call.
/// - Combat-start BLOCK stays in BeforeCombatStart (vanilla Anchor).
/// - Owner is read only from mutable instances (hooks never fire on canonical
///   instances); IsAllowed / Rarity must not touch Owner.
/// - ModifyHandDraw is a pure query (also called for previews); no side
///   effects there.
/// </summary>
[Pool(typeof(MegaCrit.Sts2.Core.Models.RelicPools.SharedRelicPool))]
public abstract class AnthonyRelicModel : CustomRelicModel
{
    protected abstract int Slot { get; }

    public override bool IsAllowed(IRunState runState)
    {
        // Fragment-pool guard: if startup failed to build the pool, the slots
        // would drop as effect-less placeholders (user report 2026-09-13 class).
        return base.IsAllowed(runState)
            && AutoAnthonyRelicsConfig.Enabled
            && AnthonyRelicRunRegistry.CurrentRunSeed is not null
            && MainFile.FragmentPool.Triggers.Count > 0;
    }

    /// <summary>Never at Neow: the run seed does not exist yet at character select.</summary>
    public override bool IsAllowedAtNeow(Player player)
    {
        return false;
    }

    protected GeneratedRelicDefinition? Definition =>
        AnthonyRelicRunRegistry.DefinitionFor(Slot, MainFile.FragmentPool);

    public override RelicRarity Rarity => Definition?.Rarity ?? RelicRarity.Common;

    // ---------- Description (per-run definition; bilingual by locale) ----------

    public override List<(string, string)>? Localization
    {
        get
        {
            var definition = Definition;
            if (definition is null)
            {
                return new RelicLoc("Generated Relic", "A relic generated by the Anthony algorithm.", RelicText.FlavorEn);
            }
            bool chinese = TranslationServer.GetLocale().StartsWith("zh", StringComparison.OrdinalIgnoreCase);
            string name = chinese ? definition.NameZhs : definition.NameEn;
            string description = chinese ? definition.DescriptionZhs : definition.DescriptionEn;
            string flavor = chinese ? RelicText.FlavorZhs : RelicText.FlavorEn;
            return new RelicLoc(name, description, flavor);
        }
    }

    // ---------- Icons (shared placeholder; per-slot art can be dropped in later) ----------

    public override string PackedIconPath => RelicImagePath($"{Id.Entry.RemovePrefix().ToLowerInvariant()}.png");

    protected override string PackedIconOutlinePath =>
        RelicImagePath($"{Id.Entry.RemovePrefix().ToLowerInvariant()}_outline.png");

    protected override string BigIconPath => BigRelicImagePath($"{Id.Entry.RemovePrefix().ToLowerInvariant()}.png");

    private static string RelicImagePath(string file)
    {
        string path = System.IO.Path.Join(MainFile.ResPath, "images", "relics", file);
        if (ResourceLoader.Exists(path))
        {
            return path;
        }
        return System.IO.Path.Join(MainFile.ResPath, "images", "relics", "relic.png");
    }

    private static string BigRelicImagePath(string file)
    {
        string path = System.IO.Path.Join(MainFile.ResPath, "images", "relics", "big", file);
        if (ResourceLoader.Exists(path))
        {
            return path;
        }
        return System.IO.Path.Join(MainFile.ResPath, "images", "relics", "big", "relic.png");
    }

    /// <summary>
    /// Hover the RELIC -> also show a tooltip for every power it applies
    /// (vanilla Akabeko pattern, user request 2026-09-13).
    /// </summary>
    protected override IEnumerable<IHoverTip> ExtraHoverTips
    {
        get
        {
            var definition = Definition;
            if (definition is null)
            {
                yield break;
            }
            foreach (var effect in definition.Effects)
            {
                if (effect.Opcode != "apply_power")
                {
                    continue;
                }
                Type? powerType = effect.Variant switch
                {
                    "vigor" => typeof(VigorPower),
                    "strength" => typeof(StrengthPower),
                    "thorns" => typeof(ThornsPower),
                    "vulnerable" => typeof(VulnerablePower),
                    _ => null,
                };
                if (powerType is null)
                {
                    continue;
                }
                var tip = s_fromPowerGeneric.Value
                    .MakeGenericMethod(powerType)
                    .Invoke(null, new object?[] { null }) as IHoverTip;
                if (tip is not null)
                {
                    yield return tip;
                }
            }
        }
    }

    /// <summary>Pick the GENERIC FromPower overload explicitly - GetMethod(name)
    /// throws AmbiguousMatchException (two overloads), which aborted the
    /// hover-tip enumeration mid-flight and left the relic detail popup unable
    /// to close.</summary>
    private static readonly Lazy<MethodInfo> s_fromPowerGeneric = new(() =>
        typeof(HoverTipFactory).GetMethods().Single(mi =>
            mi.Name == nameof(HoverTipFactory.FromPower) && mi.IsGenericMethod));

    // ---------- Trigger hooks ----------

    public override async Task BeforeCombatStart()
    {
        // Fuse (L21): this hook is awaited by the engine's turn loop; a throw
        // here marks the combat permanently stuck. Log and degrade instead.
        try
        {
            var (owner, trigger, effects) = Resolve("combat_start");
            if (owner is null || effects is null)
            {
                return;
            }
            if (!MatchesCondition(trigger!.Condition, owner))
            {
                return;
            }
            Flash();
            await ExecuteEffectsAsync(effects, owner);
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] combat-start effect suppressed to keep the combat alive: {e}");
        }
    }

    /// <summary>turn_start_early (vanilla BagOfMarbles: BeforeSideTurnStart).</summary>
    public override async Task BeforeSideTurnStart(PlayerChoiceContext choiceContext, CombatSide side,
        IReadOnlyList<Creature> participants, ICombatState combatState)
    {
        // Fuse (L21): awaited by the engine's turn loop.
        try
        {
            var (owner, trigger, effects) = Resolve("turn_start_early");
            if (owner is null || effects is null)
            {
                return;
            }
            if (!participants.Contains(owner.Creature))
            {
                return;
            }
            if (!MatchesCondition(trigger!.Condition, owner))
            {
                return;
            }
            // Enemy debuffs are ACCUMULATED across all generated relics and applied
            // as ONE merged application at the owner's first turn start (user order
            // 2026-09-13): separate low-count applications each burn one enemy
            // Artifact charge. Only the vulnerable-all fragment is enemy-facing
            // today; the bag is keyed by power type to stay extensible.
            foreach (var effect in effects.Where(e => e.Opcode == "apply_power" && e.Variant == "vulnerable"))
            {
                AccumulateEnemyDebuff<VulnerablePower>(owner, effect.Amount);
            }
            foreach (var effect in effects.Where(e => !(e.Opcode == "apply_power" && e.Variant == "vulnerable")))
            {
                await ExecuteEffectAsync(effect, owner);
            }
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] early turn-start effect suppressed to keep the combat alive: {e}");
        }
    }

    /// <summary>turn_start (vanilla Lantern: energy survives here, not in BeforeCombatStart).</summary>
    public override async Task AfterSideTurnStart(CombatSide side, IReadOnlyList<Creature> participants,
        ICombatState combatState)
    {
        // Fuse (L21): awaited by the engine's turn loop.
        try
        {
            var (owner, trigger, effects) = Resolve("turn_start");
            if (owner is null || effects is null)
            {
                return;
            }
            if (!participants.Contains(owner.Creature))
            {
                return;
            }
            // Flush the merged debuff bag BEFORE this relic's own condition gate:
            // the bag spans all generated relics, so the flush must not depend on
            // any single relic's condition passing.
            if (owner.PlayerCombatState?.TurnNumber <= 1)
            {
                await FlushEnemyDebuffs(owner);
            }
            if (!MatchesCondition(trigger!.Condition, owner))
            {
                return;
            }
            Flash();
            await ExecuteEffectsAsync(effects, owner);
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] turn-start effect suppressed to keep the combat alive: {e}");
        }
    }

    /// <summary>turn_end (vanilla Anchor-family: BeforeSideTurnEnd with participants gate).</summary>
    public override async Task BeforeSideTurnEnd(PlayerChoiceContext choiceContext, CombatSide side,
        IEnumerable<Creature> participants)
    {
        // Fuse (L21): awaited by the engine's turn loop.
        try
        {
            var (owner, trigger, effects) = Resolve("turn_end");
            if (owner is null || effects is null)
            {
                return;
            }
            if (!participants.Contains(owner.Creature))
            {
                return;
            }
            if (!MatchesCondition(trigger!.Condition, owner))
            {
                return;
            }
            Flash();
            await ExecuteEffectsAsync(effects, owner);
        }
        catch (Exception e)
        {
            MainFile.Logger.Error($"[{MainFile.ModId}] turn-end effect suppressed to keep the combat alive: {e}");
        }
    }

    public override async Task AfterRoomEntered(AbstractRoom room)
    {
        if (room is not CombatRoom)
        {
            return;
        }
        var (owner, trigger, effects) = Resolve("room_entered");
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    public override async Task AfterObtained()
    {
        var (owner, trigger, effects) = Resolve("obtained");
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    public override async Task AfterCardPlayed(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        var owner = Owner;
        var definition = Definition;
        if (owner is null || definition?.Trigger is null || definition.Trigger.Kind != "card_played")
        {
            return;
        }
        if (cardPlay.Card.Owner != owner || !CombatManager.Instance.IsInProgress)
        {
            return;
        }
        if (!MatchesCondition(definition.Trigger.Condition, owner, card: cardPlay.Card))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(definition.Effects, owner);
    }

    public override async Task AfterDeath(PlayerChoiceContext choiceContext, Creature target,
        bool wasRemovalPrevented, float deathAnimLength)
    {
        var (owner, trigger, effects) = Resolve("creature_died");
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner, target: target))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    public override async Task AfterGoldGained(Player player)
    {
        var (owner, trigger, effects) = Resolve("gold_gained");
        if (owner is null || player != owner || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    /// <summary>combat_victory (vanilla MeatOnTheBone: AfterCombatVictoryEarly).</summary>
    public override async Task AfterCombatVictoryEarly(CombatRoom room)
    {
        var (owner, trigger, effects) = Resolve("combat_victory");
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    /// <summary>combat_end trigger (ChosenCheese pattern). Also clears the
    /// enemy-debuff merge bag: a combat that ends before the owner's first
    /// turn start never reaches the flush point, and stale amounts must not
    /// leak into the next fight.</summary>
    public override async Task AfterCombatEnd(CombatRoom room)
    {
        var (owner, trigger, effects) = Resolve("combat_end");
        lock (DebuffGate)
        {
            PendingEnemyDebuffs.Clear();
        }
        if (owner is null || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    public override async Task AfterBlockCleared(Creature creature)
    {
        var (owner, trigger, effects) = Resolve("block_cleared");
        if (owner is null || creature != owner.Creature || effects is null)
        {
            return;
        }
        if (!MatchesCondition(trigger!.Condition, owner))
        {
            return;
        }
        Flash();
        await ExecuteEffectsAsync(effects, owner);
    }

    // ---------- Passive modifiers ----------

    public override decimal ModifyHandDraw(Player player, decimal count)
    {
        var owner = Owner;
        if (owner is null || player != owner)
        {
            return count;
        }
        var definition = Definition;
        if (definition is null)
        {
            return count;
        }
        foreach (EffectFragment effect in definition.Effects)
        {
            if (effect.Opcode != "modify_hand_draw")
            {
                continue;
            }
            if (!MatchesCondition(effect.Condition, owner))
            {
                continue;
            }
            count += effect.Amount;
        }
        // Floor 1: a 0-card opening hand would brick the run.
        return Math.Max(1m, count);
    }

    // ---------- Condition evaluation (stateless by design) ----------

    private bool MatchesCondition(string? condition, Player owner, CardModel? card = null, Creature? target = null)
    {
        switch (condition)
        {
            case null:
            case "":
                return true;
            case "first_turn":
                return owner.PlayerCombatState?.TurnNumber <= 1;
            case "turn_equals_2":
                return owner.PlayerCombatState?.TurnNumber == 2;
            case "turn_equals_3":
                return owner.PlayerCombatState?.TurnNumber == 3;
            case "hp_below_half":
                return owner.Creature.CurrentHp * 2m <= owner.Creature.MaxHp;
            case "hand_empty":
                return PileType.Hand.GetPile(owner).IsEmpty;
            case "no_attack_played_this_turn":
                return !CombatManager.Instance.History.CardPlaysFinished.Any(e =>
                    e.HappenedThisTurn(owner.Creature.CombatState)
                    && e.CardPlay.Card.Type == CardType.Attack
                    && e.CardPlay.Player == owner);
            case "card_type_power":
                return card is not null && card.Type == CardType.Power;
            case "enemy_side":
                return target is not null && owner.Creature is not null && target.Side != owner.Creature.Side;
            default:
                throw new InvalidOperationException($"unknown relic condition '{condition}' (ledger/generator drift)");
        }
    }

    // ---------- Enemy-debuff merge (one Apply per power per combat) ----------

    private static readonly object DebuffGate = new();
    // Keyed by OWNER IDENTITY (second-round review, 2026-09-13): in
    // multiplayer every client hosts relic instances for ALL players, and a
    // process-global bag would merge two players' debuffs into whoever's
    // turn start flushes first. ulong 0 = single-player fallback.
    // Owner-0 reachability (third-round AAR-6): the 0 bucket exists only when
    // NetId is unset, i.e. single-player, where exactly one player exists -
    // two owners can never share the 0 bucket; MP players always carry real
    // NetIds. Bags flush on their owner's turn start and the whole map clears
    // on combat end; StS2 has no overlapping combat states.
    private static readonly Dictionary<ulong, Dictionary<Type, int>> PendingEnemyDebuffs = new();

    private static ulong OwnerKey(Player? owner) => owner?.NetId ?? 0;

    private void AccumulateEnemyDebuff<T>(Player owner, int amount) where T : PowerModel
    {
        if (amount <= 0)
        {
            return;
        }
        lock (DebuffGate)
        {
            var bag = PendingEnemyDebuffs.TryGetValue(OwnerKey(owner), out var existing)
                ? existing
                : (PendingEnemyDebuffs[OwnerKey(owner)] = new Dictionary<Type, int>());
            bag[typeof(T)] = bag.GetValueOrDefault(typeof(T)) + amount;
        }
    }

    private static async Task FlushEnemyDebuffs(Player owner)
    {
        KeyValuePair<Type, int>[] pending;
        lock (DebuffGate)
        {
            if (!PendingEnemyDebuffs.TryGetValue(OwnerKey(owner), out var bag)
                || bag.Count == 0)
            {
                return;
            }
            pending = bag.ToArray();
            PendingEnemyDebuffs.Remove(OwnerKey(owner));
        }
        var context = new ThrowingPlayerChoiceContext();
        var enemies = owner.Creature.CombatState?.HittableEnemies ?? Array.Empty<Creature>();
        if (enemies.Count == 0)
        {
            return;
        }
        foreach (var entry in pending)
        {
            var closed = s_vulnerableApply.MakeGenericMethod(entry.Key);
            // SIX arguments: the optional `bool silent = false` is the 6th
            // parameter, and MethodInfo.Invoke does NOT fill optional-param
            // defaults - the 5-arg call threw TargetParameterCountException
            // inside the engine's turn loop and froze the combat (Act 4
            // report 2026-09-13).
            var task = (Task)closed.Invoke(null,
                new object?[] { context, enemies, (decimal)entry.Value, owner.Creature, null, false })!;
            await task;
        }
    }

    private static readonly MethodInfo s_vulnerableApply =
        typeof(PowerCmd).GetMethods()
            .Single(m => m.Name == nameof(PowerCmd.Apply)
                && m.IsGenericMethod
                && m.GetParameters()[1].ParameterType == typeof(IEnumerable<Creature>));

    // ---------- Effect execution ----------

    private (Player? owner, TriggerFragment? trigger, IReadOnlyList<EffectFragment>? effects) Resolve(string kind)
    {
        var definition = Definition;
        Player? owner = Owner;
        if (definition?.Trigger is null || owner is null || definition.Trigger.Kind != kind)
        {
            return (null, null, null);
        }
        return (owner, definition.Trigger, definition.Effects);
    }

    // Combat-scoped opcodes (matched by opcode alone): their engine commands
    // need a live combat context (energy / enemies / draw pile) and NRE
    // outside combat - an Ancient-event pickup fired gain_energy with no
    // PlayerCombatState, killing the obtain chain and freezing the game's UI
    // in a render loop (real incident 2026-09-14). Run-scoped opcodes (heal,
    // gain_max_hp, gain_gold, gain_max_potion, modify_hand_draw) are safe.
    private static readonly HashSet<string> CombatScopedOpcodes = new(StringComparer.Ordinal)
    {
        "apply_power", "gain_block", "gain_energy", "draw_cards", "deal_damage",
    };

    private async Task ExecuteEffectsAsync(IReadOnlyList<EffectFragment> effects, Player owner)
    {
        var context = new ThrowingPlayerChoiceContext();
        foreach (EffectFragment effect in effects)
        {
            try
            {
                await ExecuteEffectAsync(effect, owner, context);
            }
            catch (Exception e)
            {
                // Per-effect fuse: one broken effect must not break the whole
                // obtain chain / trigger pipeline (2026-09-14 freeze incident).
                MainFile.Logger.Error($"[{MainFile.ModId}] effect {effect.Opcode}/{effect.Variant} failed; continuing: {e.Message}");
            }
        }
    }

    private async Task ExecuteEffectAsync(EffectFragment effect, Player owner,
        ThrowingPlayerChoiceContext? context = null)
    {
        context ??= new ThrowingPlayerChoiceContext();
        {
            if (CombatScopedOpcodes.Contains(effect.Opcode) && owner.PlayerCombatState is null)
            {
                // Out-of-combat guard: this trigger fired outside any combat
                // (obtain / room-entered / run-level hooks) - the combat-scoped
                // command would NRE, so degrade to a skipped effect instead.
                MainFile.Logger.Info($"[{MainFile.ModId}] effect {effect.Opcode}/{effect.Variant} skipped: no combat context at this trigger");
                return;
            }
            int amount = effect.Amount;
            switch (effect.Opcode, effect.Variant, effect.Target)
            {
                case ("apply_power", "vigor", "self"):
                    await PowerCmd.Apply<VigorPower>(context, owner.Creature, amount, owner.Creature, null);
                    break;
                case ("apply_power", "strength", "self"):
                    await PowerCmd.Apply<StrengthPower>(context, owner.Creature, amount, owner.Creature, null);
                    break;
                case ("apply_power", "thorns", "self"):
                    await PowerCmd.Apply<ThornsPower>(context, owner.Creature, amount, owner.Creature, null);
                    break;
                case ("apply_power", "vulnerable", "all_enemies"):
                    await PowerCmd.Apply<VulnerablePower>(context,
                        owner.Creature.CombatState?.HittableEnemies ?? Array.Empty<Creature>(),
                        amount, owner.Creature, null);
                    break;
                case ("gain_block", _, "self"):
                    await CreatureCmd.GainBlock(owner.Creature, amount, ValueProp.Unpowered, null);
                    break;
                case ("heal", _, "self"):
                    await CreatureCmd.Heal(owner.Creature, amount);
                    break;
                case ("gain_energy", _, "self"):
                    await PlayerCmd.GainEnergy(amount, owner);
                    break;
                case ("draw_cards", _, "self"):
                    await CardPileCmd.Draw(context, amount, owner);
                    break;
                case ("gain_max_hp", _, "self"):
                    await CreatureCmd.GainMaxHp(owner.Creature, amount);
                    break;
                case ("gain_gold", _, "self"):
                    await PlayerCmd.GainGold(amount, owner);
                    break;
                case ("gain_max_potion", _, "self"):
                    await PlayerCmd.GainMaxPotionCount(amount, owner);
                    break;
                case ("deal_damage", _, "all_enemies"):
                    await CreatureCmd.Damage(context,
                        owner.Creature.CombatState?.HittableEnemies ?? Array.Empty<Creature>(),
                        amount, ValueProp.Unpowered, owner.Creature, null, null);
                    break;
                case ("modify_hand_draw", _, "self"):
                    // Handled by the ModifyHandDraw query override; nothing to run.
                    break;
                default:
                    throw new InvalidOperationException(
                        $"unsupported relic effect {effect.Opcode}/{effect.Variant}/{effect.Target} on atom {effect.SourceAtom}");
            }
        }
    }
}
